swagger: '2.0'
info:
  description: >-
    This API gives everyone a good laugh--hopefully.
  version: 1.0.0
  title: Dad Jokes API
  termsOfService: ''
  contact:
    email: shayneburgess@github.com
basePath: /dad/
tags:
  - name: jokes
    description: Endpoints for jokes.
schemes:
  - http
  - https
paths:

  /jokes/{id}:
    get:
      tags:
        - jokes
      summary: Tell me a joke.
      description: Get a grade A Dad joke (honestly, some of them aren't grade A, but that makes them better)
      operationId: getDadJoke
      parameters:
        - in: path
          name: id
          type: integer
          format: int64
          required: true
          description: The ID of the Dad Joke
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/DadJoke'
        '400':
          description: Invalid status value
          schema:
            $ref: '#/definitions/Error'
  /jokes:
    post:
      tags:
        - jokes
      summary: Add your own joke
      description: Dad jokes are for everyone, we want to know yours!
      operationId: createDadJoke
      parameters:
        - in: body
          name: dadJokeRequest
          schema:
            $ref: '#/definitions/DadJoke'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/DadJoke'
        '400':
          description: Invalid status value
          schema:
            $ref: '#/definitions/Error'

definitions:

  ########################################################################################################################
  # Contracts ############################################################################################################
  ########################################################################################################################

  DadJoke:
    type: object
    required:
      - question
      - answer
    properties:
      id:
        type: integer
        format: int32
      question:
        type: string
      answer:
        type: string

  ########################################################################################################################
  # Errors ###############################################################################################################
  ########################################################################################################################

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      body:
        type: object

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
