name: Build and push devcontainer base image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push the Docker image
        run: IMAGE_TAG=$(echo ghcr.io/shayneburgess/java-trial/devcontainer:latest) && docker build -t $IMAGE_TAG -f python/Dockerfile . && docker login https://ghcr.io -u shayneburgess -p ${{ secrets.GITHUB_TOKEN }} && docker push $IMAGE_TAG
